In [2]:
# Importing all necessary libraries
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn import metrics

In [3]:
# Importing data
train = pd.read_csv("Final_project_DATA/df_train.csv")
test = pd.read_csv("Final_project_DATA/df_test.csv")

In [4]:
# Splitting the labels from the rest
X_train = train.drop('type', axis = 1)
y_train = train['type']
X_test = test.drop('type',axis = 1)
y_test = test['type']

## Grid search for optimal hyper parameteres

In [ ]:
from sklearn.model_selection import GridSearchCV

#Create a dictionary called param_grid and fill out some parameters for kernels, C and gamma
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001],'kernel': ['rbf']}

#Create a GridSearchCV object and fit it to the training data
svc = svm.SVC()
grid = GridSearchCV(svc,param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)

In [15]:
#Optimal combination of hyper parameteres
print(grid.best_estimator_)

SVC(C=100, gamma=0.01)


## Model creation and evaluation

In [10]:
# This is the Radial Basis Function kernel with the optimal hyper parameters
rbf = svm.SVC(C=100, kernel='rbf', gamma=0.01, decision_function_shape='ovo').fit(X_train, y_train)

In [11]:
# Make predictions on test set
rbf_pred = rbf.predict(X_test)

In [12]:
# Retrieve the accuracy and print it
accuracy_rbf = rbf.score(X_test, y_test)
print('Accuracy Radial Basis Kernel:', accuracy_rbf)

Accuracy Radial Basis Kernel: 0.7384615384615385


In [16]:
print(confusion_matrix(y_test,rbf_pred))

[[19  2  0  0  0  0]
 [ 4 16  0  2  1  0]
 [ 2  3  0  0  0  0]
 [ 0  0  0  4  0  0]
 [ 1  0  0  0  2  0]
 [ 1  0  0  1  0  7]]


In [13]:
print(classification_report(y_test, rbf_pred))

              precision    recall  f1-score   support

           1       0.70      0.90      0.79        21
           2       0.76      0.70      0.73        23
           3       0.00      0.00      0.00         5
           5       0.57      1.00      0.73         4
           6       0.67      0.67      0.67         3
           7       1.00      0.78      0.88         9

    accuracy                           0.74        65
   macro avg       0.62      0.67      0.63        65
weighted avg       0.70      0.74      0.71        65



D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
