In [38]:
from sklearn import preprocessing 
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import metrics
import math

In [149]:
train = pd.read_csv("Final_project_DATA/df_train.csv")
test = pd.read_csv("Final_project_DATA/df_test.csv")

In [150]:
X_train = train.drop('type', axis = 1)
y_train = train['type']
X_test = test.drop('type',axis = 1)
y_test = test['type']

In [151]:
scaler = preprocessing.MaxAbsScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [152]:
X_train

array([[0.98986916, 0.73935558, 0.92211055, ..., 0.53613342, 0.        ,
        0.94594595],
       [0.99144681, 0.79286536, 0.57286432, ..., 0.60840025, 0.        ,
        0.45945946],
       [0.98901514, 0.78941312, 0.92462312, ..., 0.4867202 , 0.        ,
        0.        ],
       ...,
       [0.99329826, 0.90851554, 0.45979899, ..., 0.53180976, 0.53333333,
        0.        ],
       [0.98812201, 0.73187572, 0.86934673, ..., 0.49969117, 0.        ,
        0.64864865],
       [0.98952364, 0.73245109, 0.86180905, ..., 0.54107474, 0.        ,
        0.81081081]])

## Dim reduction PCA

In [153]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 3)
x_pca = pca.fit_transform(X_train)

from sklearn.decomposition import PCA
pca_test = PCA(n_components = 3)
x_pca_test = pca_test.fit_transform(X_test)

In [154]:
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.54544521 0.24929576 0.10988805]


In [155]:
print(int(math.sqrt(len(train))))

12


In [156]:
# train point 
k=int(math.sqrt(len(train)))
knn_clf=KNeighborsClassifier(n_neighbors = k)
knn_clf.fit(x_pca,y_train)
y_pred=knn_clf.predict(x_pca_test) #These are the predicted output values

In [157]:
y_pred

array([1, 1, 1, 7, 1, 7, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 6, 1, 2, 6, 7, 7,
       2, 2, 2, 2, 2, 1, 2, 7, 2, 1, 1, 1, 5, 1, 2, 7, 1, 2, 1, 2, 7, 1,
       7, 1, 7, 1, 1, 1, 2, 1, 1, 1, 1, 7, 1, 2, 1, 7, 1, 1, 1, 2, 1],
      dtype=int64)

In [158]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix: ')
print(conf_matrix)
rep = classification_report(y_test, y_pred)
print('Classification Report:',)
print (rep)
acc = accuracy_score(y_test,y_pred)
print('Accuracy:',acc)

Confusion Matrix: 
[[18  3  0  0  0  0]
 [11 10  0  0  0  2]
 [ 2  3  0  0  0  0]
 [ 0  1  0  0  0  3]
 [ 2  1  0  0  0  0]
 [ 0  0  0  1  2  6]]
Classification Report:
              precision    recall  f1-score   support

           1       0.55      0.86      0.67        21
           2       0.56      0.43      0.49        23
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         3
           7       0.55      0.67      0.60         9

    accuracy                           0.52        65
   macro avg       0.27      0.33      0.29        65
weighted avg       0.45      0.52      0.47        65

Accuracy: 0.5230769230769231


D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
