In [44]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn import metrics

In [35]:
train = pd.read_csv("Final_project_DATA/df_train.csv")
test = pd.read_csv("Final_project_DATA/df_test.csv")

In [36]:
X_train = train.drop('type', axis = 1)
y_train = train['type']
X_test = test.drop('type',axis = 1)
y_test = test['type']

In [37]:
# Normalising data
X_train_norm = preprocessing.normalize(X_train)
X_test_norm = preprocessing.normalize(X_test)
print("Normalized Data Train = ", X_train_norm)
print("Normalized Data Test = ", X_test_norm)

Normalized Data Train =  [[0.02042817 0.17288178 0.04937557 ... 0.11677929 0.         0.00470884]
 [0.0205453  0.1861602  0.03080154 ... 0.13306807 0.         0.00229661]
 [0.02052639 0.18563427 0.04979112 ... 0.10661793 0.         0.        ]
 ...
 [0.02094051 0.21701221 0.02515088 ... 0.11833281 0.02308933 0.        ]
 [0.02024965 0.16993725 0.04622507 ... 0.10808116 0.         0.00320636]
 [0.02032604 0.17047057 0.04593198 ... 0.11730732 0.         0.00401737]]
Normalized Data Test =  [[2.06246130e-02 1.84955866e-01 6.08835658e-02 1.49157956e-02
  9.73323464e-01 8.13588852e-04 1.18648374e-01 0.00000000e+00
  0.00000000e+00]
 [2.02962598e-02 1.72166584e-01 4.65532022e-02 1.77918848e-02
  9.77082152e-01 7.49131990e-03 1.12771119e-01 0.00000000e+00
  0.00000000e+00]
 [2.05964527e-02 1.92280287e-01 5.16897042e-02 6.35972801e-03
  9.71143998e-01 1.48844698e-03 1.29494887e-01 0.00000000e+00
  0.00000000e+00]
 [2.01006216e-02 1.88249030e-01 0.00000000e+00 3.69869573e-02
  9.73857306e-01 5.

In [38]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
x_pca = pca.fit_transform(X_train_norm)
x_pca = pd.DataFrame(x_pca)

from sklearn.decomposition import PCA
pca_test = PCA(n_components = 2)
x_pca_test = pca_test.fit_transform(X_test_norm)
x_pca_test = pd.DataFrame(x_pca_test)

In [39]:
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.52581133 0.28898602]


In [173]:
# train
knn_clf=KNeighborsClassifier(n_neighbors = 14, weights = 'uniform', algorithm = 'auto', metric = 'minkowski')
# Defaults: (n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None,
# n_jobs=None)
knn_clf.fit(x_pca,y_train)
y_pred=knn_clf.predict(x_pca_test) #These are the predicted output values

In [174]:
y_pred

array([2, 2, 1, 7, 1, 7, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 7, 2, 2, 7, 7, 7,
       1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 7, 2, 2, 1, 2, 7, 2,
       5, 2, 5, 2, 1, 2, 5, 2, 2, 1, 2, 5, 2, 2, 2, 7, 1, 2, 2, 1, 2],
      dtype=int64)

In [175]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print('Confusion Matrix: ')
print(result)
result1 = classification_report(y_test, y_pred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print('Accuracy:',result2)

Confusion Matrix: 
[[ 9 12  0  0  0  0]
 [ 3 18  0  2  0  0]
 [ 3  2  0  0  0  0]
 [ 0  1  0  2  0  1]
 [ 3  0  0  0  0  0]
 [ 1  0  0  0  0  8]]
Classification Report:
              precision    recall  f1-score   support

           1       0.47      0.43      0.45        21
           2       0.55      0.78      0.64        23
           3       0.00      0.00      0.00         5
           5       0.50      0.50      0.50         4
           6       0.00      0.00      0.00         3
           7       0.89      0.89      0.89         9

    accuracy                           0.57        65
   macro avg       0.40      0.43      0.41        65
weighted avg       0.50      0.57      0.53        65

Accuracy: 0.5692307692307692


D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\flavi\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
